#ifndef TASKSCHEDULER_GLOBAL_H
#define TASKSCHEDULER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TASKSCHEDULER_LIBRARY)
#  define TASKSCHEDULER_EXPORT Q_DECL_EXPORT
#else
#  define TASKSCHEDULER_EXPORT Q_DECL_IMPORT
#endif

#endif // TASKSCHEDULER_GLOBAL_H