#ifndef LOGGERMONITOR_GLOBAL_H
#define LOGGERMONITOR_GLOBAL_H
#include <QtCore/qglobal.h>

#ifdef LOGGERMONITOR_LIBRARY
#define LOGGERMONITOR_EXPORT Q_DECL_EXPORT
#else
#define LOGGERMONITOR_EXPORT Q_DECL_IMPORT
#endif

#endif // LOGGERMONITOR_GLOBAL_H
