#ifndef QSINGLEAPPLICATION_GLOBAL_H
#define QSINGLEAPPLICATION_GLOBAL_H
#include <QtCore/qglobal.h>

#if defined(QSINGLEAPPLICATION_LIBRARY)
#  define QSINGLEAPPLICATION_EXPORT Q_DECL_EXPORT
#else
#  define QSINGLEAPPLICATION_EXPORT Q_DECL_IMPORT
#endif

#endif // QSINGLEAPPLICATION_GLOBAL_H
