#ifndef QMODBUSRTUUNIT_GLOBAL_H
#define QMODBUSRTUUNIT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QMODBUSRTUUNIT_LIBRARY
#define QMODBUSRTUUNIT_EXPORT Q_DECL_EXPORT
#else
#define QMODBUSRTUUNIT_EXPORT Q_DECL_IMPORT
#endif

#endif // QMODBUSRTUUNIT_GLOBAL_H