#ifndef CONFIGMANAGER_GLOBAL_H
#define CONFIGMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CONFIGMANAGER_LIBRARY
#define CONFIGMANAGER_EXPORT Q_DECL_EXPORT
#else
#define CONFIGMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // CONFIGMANAGER_GLOBAL_H