#ifndef FILEEXPORTER_GLOBAL_H
#define FILEEXPORTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FILEEXPORTER_LIBRARY
#define FILEEXPORTER_EXPORT Q_DECL_EXPORT
#else
#define FILEEXPORTER_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEEXPORTER_GLOBAL_H